# Site settings
baseurl = "/"
languageCode = "en-us"
title = "NIME 2017 Workshop on Skill Learning and Interactive Music Technology"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "Skill Learning and <br>Interactive Music Technology"
    subtitle = '<span style="margin-top:0px;font-size:30px;color:#A1335E;font-weight:300;margin-bottom:-30px;">A NIME 2017 Workshop â€” May 15, 2017</span>'
    description = ""
    keywords = "Hugo, Hugo theme, grid theme, portfolio, bookmarks, collection, contacts"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Get the theme"

    # Footer text
    footertext = ""

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
